name: Dependabot auto-merge

on:
  workflow_call:
    secrets:
      DEPENDABOT_AUTO_MERGE_APP_ID:
        description: 'GitHub App ID for Dependabot auto-merge'
        required: true
      DEPENDABOT_AUTO_MERGE_APP_SECRET:
        description: 'GitHub App private key for Dependabot auto-merge'
        required: true

permissions:
  contents: read
  pull-requests: read

jobs:
  dependabot:
    name: Auto-merge Dependabot PR
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.actor == 'dependabot[bot]'
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@08eff52bf64351f401fb50d4972fa95b9f2c2d1b # ratchet:dependabot/fetch-metadata@v2.4.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate token
        id: app-token
        uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # ratchet:actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.DEPENDABOT_AUTO_MERGE_APP_ID }}
          private-key: ${{ secrets.DEPENDABOT_AUTO_MERGE_APP_SECRET }}

      - name: Authenticate gh CLI
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: echo "$GH_TOKEN" | gh auth login --with-token

      - name: Enable auto-merge for Dependabot PRs
        if: steps.metadata.outputs.update-type != 'version-update:semver-major'
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
        run: gh pr merge --auto --squash "$PR_URL"
